spring:
  application:
    name: filefeed-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/yourdb
    username: yourusername
    password: yourpassword
    liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-master.yaml
