spring:
  application:
    name: filefeed-service

  servlet:
    webflux:
      multipart:
        enabled: true
        max-file-size: 10MB  # Adjust as per your requirement
        max-request-size: 10MB

  r2dbc:
    url: r2dbc:h2:file:///./data/h2db/testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:h2:file:./data/h2db/testdb
    user: sa
    password: sa

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet: DEBUG
#    org.springframework.web.reactive: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true